/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    categories: Category;
    products: Product;
    'rma-requests': RmaRequest;
    carousels: Carousel;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'rma-requests': RmaRequestsSelect<false> | RmaRequestsSelect<true>;
    carousels: CarouselsSelect<false> | CarouselsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Auto-generated from filename if not provided
   */
  alt: string;
  /**
   * SHA-256 hash of the file for duplicate detection
   */
  hash?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generated from name, or enter custom slug (URL-unsafe characters will be replaced)
   */
  slug?: string | null;
  /**
   * Parent category (leave empty for top-level categories)
   */
  parent?: (number | null) | Category;
  /**
   * Type of category for filtering purposes
   */
  type?:
    | (
        | 'product-category'
        | 'resolution'
        | 'series'
        | 'accessories-type'
        | 'channels'
        | 'port'
        | 'server-series'
        | 'capacity'
        | 'voltage'
        | 'input-type'
        | 'size'
      )
    | null;
  /**
   * Optional description for this category
   */
  description?: string | null;
  /**
   * Category header image (especially for Product Category type)
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Product model number or name
   */
  model: string;
  /**
   * Auto-generated from model, or enter custom slug (URL-unsafe characters will be replaced)
   */
  slug?: string | null;
  /**
   * Detailed product description
   */
  description?: string | null;
  /**
   * Select the main product category (e.g., IP Cameras, NVR, etc.)
   */
  mainCategory: number | Category;
  /**
   * Select subcategories by type. Only available types for the selected main category will be shown.
   */
  subcategories?: {
    /**
     * Select resolution categories
     */
    resolutions?: (number | Category)[] | null;
    /**
     * Select series categories
     */
    series?: (number | Category)[] | null;
    /**
     * Select accessories type categories
     */
    accessoriesTypes?: (number | Category)[] | null;
    /**
     * Select channel categories
     */
    channels?: (number | Category)[] | null;
    /**
     * Select port categories
     */
    ports?: (number | Category)[] | null;
    /**
     * Select server series categories
     */
    serverSeries?: (number | Category)[] | null;
    /**
     * Select capacity categories
     */
    capacities?: (number | Category)[] | null;
    /**
     * Select voltage categories
     */
    voltages?: (number | Category)[] | null;
    /**
     * Select input type categories
     */
    inputTypes?: (number | Category)[] | null;
    /**
     * Select size categories
     */
    sizes?: (number | Category)[] | null;
  };
  /**
   * Auto-populated: All categories (main + subcategories)
   */
  categories?: (number | Category)[] | null;
  /**
   * Add related products (e.g., accessories for main products, or main products for accessories)
   */
  relatedProducts?:
    | {
        /**
         * Select a related product
         */
        product: number | Product;
        /**
         * Specify the type of relationship
         */
        relationType: 'accessory' | 'compatible' | 'alternative' | 'upgrade' | 'related';
        /**
         * Optional note about this relationship (e.g., "Recommended for outdoor installation")
         */
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Additional product details and information
   */
  details?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  details_html?: string | null;
  /**
   * Product specifications and technical details
   */
  specification?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  specification_html?: string | null;
  /**
   * Upload PDF files, datasheets, manuals, etc.
   */
  downloads?:
    | {
        file: number | Media;
        /**
         * Display name for the download (e.g., "Product Datasheet", "User Manual")
         */
        title: string;
        /**
         * Optional description of the download file
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Product images. The first image will be used as the featured image. Use "Bulk Upload Images" button to upload multiple images at once.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Alt text for the image (auto-generated from filename if not provided)
         */
        alt?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Visible products will be shown on the frontend, hidden products will be filtered out
   */
  status?: ('visible' | 'hidden') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * RMA (Return Merchandise Authorization) and Technical Support requests submitted by customers
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma-requests".
 */
export interface RmaRequest {
  id: number;
  firstName: string;
  lastName: string;
  /**
   * Customer email address for communication
   */
  email: string;
  requestType: 'rma' | 'tech-support';
  onSite: 'yes' | 'no';
  phoneNumber: string;
  companyName?: string | null;
  address: {
    line1: string;
    line2?: string | null;
    city: string;
    state: string;
    zipCode: string;
  };
  invoiceDate?: string | null;
  invoiceNumber?: string | null;
  serialNumber: string;
  model?: string | null;
  /**
   * If not applicable, please write n/a
   */
  deviceLoginUsername: string;
  distributor?: string | null;
  subject: string;
  /**
   * Upload supporting documents, images, or files related to the RMA request
   */
  attachments?:
    | {
        file: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Please describe the problem in detail
   */
  problem: string;
  /**
   * Current status of the RMA request
   */
  status?: ('new' | 'in-progress' | 'resolved' | 'closed') | null;
  /**
   * Internal notes for admin use only
   */
  adminNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manage homepage carousel slides
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousels".
 */
export interface Carousel {
  id: number;
  /**
   * Internal title for identification (not displayed on frontend)
   */
  title: string;
  /**
   * Carousel slide image
   */
  image: number | Media;
  /**
   * Alternative text for SEO and accessibility
   */
  altText?: string | null;
  /**
   * Enable click to configure link behavior
   */
  isClickable?: boolean | null;
  /**
   * URL to navigate when clicked
   */
  linkUrl?: string | null;
  /**
   * How to open the link
   */
  linkTarget?: ('_self' | '_blank') | null;
  /**
   * Lower numbers appear first
   */
  order?: number | null;
  /**
   * Only active slides will be displayed on homepage
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'rma-requests';
        value: number | RmaRequest;
      } | null)
    | ({
        relationTo: 'carousels';
        value: number | Carousel;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  hash?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  type?: T;
  description?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  model?: T;
  slug?: T;
  description?: T;
  mainCategory?: T;
  subcategories?:
    | T
    | {
        resolutions?: T;
        series?: T;
        accessoriesTypes?: T;
        channels?: T;
        ports?: T;
        serverSeries?: T;
        capacities?: T;
        voltages?: T;
        inputTypes?: T;
        sizes?: T;
      };
  categories?: T;
  relatedProducts?:
    | T
    | {
        product?: T;
        relationType?: T;
        note?: T;
        id?: T;
      };
  details?: T;
  details_html?: T;
  specification?: T;
  specification_html?: T;
  downloads?:
    | T
    | {
        file?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  gallery?:
    | T
    | {
        image?: T;
        alt?: T;
        id?: T;
      };
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rma-requests_select".
 */
export interface RmaRequestsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  requestType?: T;
  onSite?: T;
  phoneNumber?: T;
  companyName?: T;
  address?:
    | T
    | {
        line1?: T;
        line2?: T;
        city?: T;
        state?: T;
        zipCode?: T;
      };
  invoiceDate?: T;
  invoiceNumber?: T;
  serialNumber?: T;
  model?: T;
  deviceLoginUsername?: T;
  distributor?: T;
  subject?: T;
  attachments?:
    | T
    | {
        file?: T;
        id?: T;
      };
  problem?: T;
  status?: T;
  adminNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carousels_select".
 */
export interface CarouselsSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  altText?: T;
  isClickable?: T;
  linkUrl?: T;
  linkTarget?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}